// Dummy Users Data:
const defaultUsers = [
  {
    name: 'Nazmul Huda',
    email: 'nazmul@gmail.com',
    phoneNumber: '01746243302',
    password: 'Nazmul@01',
    avatar: 'https://i.ibb.co/phfxcsS/pro-nazmul.webp',
    role: 'admin',
  },
  {
    name: 'Tayab Pabel',
    email: 'pabel@gmail.com',
    phoneNumber: '01746243304',
    password: 'Pabel@01',
    avatar: 'https://i.ibb.co/phfxcsS/pro-nazmul.webp',
  },
]

const demoProperties = [
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'Kadamtala',
      addressLine2: 'Bashabo',
      city: 'Dhaka',
      country: 'Bangladesh',
      postCode: '1201',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: false,
      balcony: true,
      parking: true,
      garage: false,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: false,
      electricity: true,
      generator: true,
      solar: false,
      airConditioning: false,
      swimmingPool: false,
      garden: true,
      gym: false,
      elevator: false,
      cableTv: true,
      internet: true,
      laundry: false,
      cleaningService: false,
      cafetoria: false,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: false,
      conferenceRoom: true,
      staffRoom: false,
      servantRoom: false,
    },
    postType: 'basic',
    purpose: 'rent',
    propertyCategory: 'residential',
    propertyType: 'apartment',
    propertyTitle: 'Two bedrooms apartment',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode",
    propertyPrice: 25000,
    propertyBedrooms: 2,
    propertyBathrooms: 2,
    propertyFloorNumber: 1,
    propertySqft: 1000,
    propertyFurnished: true,
    propertyFeaturedImage:
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_19_0000.jpg',
    propertyFloorPlanImage:
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_FLP_00_0000.png',
    propertyImages: [
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_01_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_02_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_03_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_04_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_05_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_06_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_07_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_08_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_09_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_11_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_12_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_13_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_14_0000.jpg',
      'https://media.rightmove.co.uk/223k/222812/93269894/222812_Deluxestudiotolet2_IMG_15_0000.jpg',
    ],
    agentName: 'Benham and Reeves',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(634289).png',
    agentPhoneNumber: '+44 20 3463 7502',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'Shangkar',
      addressLine2: 'Dhanmondi',
      city: 'Dhaka',
      country: 'Bangladesh',
      postCode: '1215',
    },
    propertyFeatures: {
      gasline: true,
      reception: true,
      tiledFloor: true,
      terrace: true,
      balcony: false,
      parking: true,
      garage: false,
      fireExit: false,
      fireProtection: true,
      water: true,
      hotWater: true,
      electricity: false,
      generator: true,
      solar: false,
      airConditioning: false,
      swimmingPool: false,
      garden: true,
      gym: false,
      elevator: false,
      cableTv: true,
      internet: false,
      laundry: true,
      cleaningService: false,
      cafetoria: false,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: false,
      conferenceRoom: true,
      staffRoom: false,
      servantRoom: false,
    },
    postType: 'featured',
    purpose: 'buy',
    propertyCategory: 'commercial',
    propertyType: 'office',
    propertyTitle: '1500 sqft office space',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 500000,
    propertyBedrooms: 3,
    propertyBathrooms: 4,
    propertyFloorNumber: 2,
    propertySqft: 5000,
    propertyFurnished: true,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/1d8140ccafbc9a74c24ddcbcfe106dadb60a35f9.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/5ac419c9b9ce049394ffada5fc169125d52c2f8e.jpg',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/1d8140ccafbc9a74c24ddcbcfe106dadb60a35f9.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/201752475cbd7f0b81c62f3c1b2d260c99ceb484.jpg:p',
      'https://media.rightmove.co.uk/223k/222812/9https://lid.zoocdn.com/u/2400/1800/ac8f46b05cd2732502a1e7c3ebeb065b7e9fd412.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/fb3bdd4effe96f3881868ee1c7a5e48b1e8d8a6e.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/5fcac4362c25767b565fcad584e696379b5c9c70.jpg:p',
    ],
    agentName: 'Ability Estate',
    agentLogo: 'https://media.rightmove.co.uk/company/clogo_55937_0000.png',
    agentPhoneNumber: '+44 20 3463 7503',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'Gulshan 2',
      addressLine2: 'Gulshan',
      city: 'Dhaka',
      country: 'Bangladesh',
      postCode: '1235',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: false,
      balcony: true,
      parking: true,
      garage: true,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: true,
      electricity: false,
      generator: true,
      solar: false,
      airConditioning: false,
      swimmingPool: false,
      garden: true,
      gym: true,
      elevator: false,
      cableTv: true,
      internet: false,
      laundry: false,
      cleaningService: false,
      cafetoria: false,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: true,
      conferenceRoom: true,
      staffRoom: false,
      servantRoom: false,
    },
    postType: 'basic',
    purpose: 'rent',
    propertyCategory: 'residential',
    propertyType: 'plot',
    propertyTitle: 'Four bedrooms apartment',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 60000,
    propertyBedrooms: 4,
    propertyBathrooms: 4,
    propertyFloorNumber: 9,
    propertySqft: 1800,
    propertyFurnished: true,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/ef862061123c932db8d764f08790ac062b6aa3c5.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/1b148de0c359375db2c8ddb2dd9cf135f492535c.png',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/ef862061123c932db8d764f08790ac062b6aa3c5.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/66f7e84d5a5aacdb4bd59ad18a0a2ed195f83b3a.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/b2cffb0d4d5633caad0f379a2b31ce60795dc7b3.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/9aa1aaf809bf99f731bf2f6b141edf462736c01d.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/f7cd6b9975bcab91a00e9f797f55b34f0d500f41.jpg:p',
    ],
    agentName: 'A to Z Property Service',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(254479).png',
    agentPhoneNumber: '+44 20 3463 2575',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'Nasirabad Housing Society',
      addressLine2: 'Muradpur',
      city: 'Chattogram',
      country: 'Bangladesh',
      postCode: '2215',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: false,
      balcony: true,
      parking: true,
      garage: false,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: false,
      electricity: true,
      generator: true,
      solar: false,
      airConditioning: false,
      swimmingPool: true,
      garden: true,
      gym: false,
      elevator: false,
      cableTv: true,
      internet: false,
      laundry: false,
      cleaningService: true,
      cafetoria: false,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: false,
      conferenceRoom: true,
      staffRoom: false,
      servantRoom: true,
    },
    postType: 'basic',
    purpose: 'rent',
    propertyCategory: 'residential',
    propertyType: 'apartment',
    propertyTitle: '1200 sqft apartment',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 20000,
    propertyBedrooms: 3,
    propertyBathrooms: 2,
    propertyFloorNumber: 6,
    propertySqft: 1200,
    propertyFurnished: false,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/ab0e2dbedeb6f312a887642e00ce50050505f9bb.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/ca66433bcee487fe9d36f348771a464fe255be41.jpg',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/25304a63ba6b36801f14e65fa207883c6f5aa9ba.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/3341227ede01d2ec26fba5a5dc0cf688f99637a4.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/5d90528f90f52a22ddabe82fa7d3769c0e3ea883.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/b544def7ffd7e75348414b9950bb9948f0b01a76.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/84250b7cd1a7031a337893fdd070d2162f7b556e.jpg:p',
    ],
    agentName: 'Abacus Estates',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(554303).png',
    agentPhoneNumber: '+44 20 3584 2575',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'Sugandha Residential Area',
      addressLine2: 'Panchlaish',
      city: 'Chattogram',
      country: 'Bangladesh',
      postCode: '2230',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: true,
      balcony: true,
      parking: true,
      garage: false,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: true,
      electricity: true,
      generator: true,
      solar: false,
      airConditioning: true,
      swimmingPool: true,
      garden: true,
      gym: false,
      elevator: false,
      cableTv: true,
      internet: false,
      laundry: false,
      cleaningService: true,
      cafetoria: true,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: true,
      conferenceRoom: true,
      staffRoom: false,
      servantRoom: true,
    },
    postType: 'basic',
    purpose: 'buy',
    propertyCategory: 'residential',
    propertyType: 'plot',
    propertyTitle: '1800 sqft plot',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 400000,
    propertyBedrooms: 4,
    propertyBathrooms: 4,
    propertyFloorNumber: 3,
    propertySqft: 1800,
    propertyFurnished: true,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/39609da71054397a3bb3468fde486c8b95e7ef15.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/c63c766f2fd54a24ed1773d20bbd3f3a475d9559.jpg',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/39609da71054397a3bb3468fde486c8b95e7ef15.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/51fafc02e69fb7918b8528ec14c652db10da7784.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/d5824f1daf85f19fade987121262a257678fbdfa.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/3208983518969ee1b5a063579f3128afc91c3c7d.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/31aaa6e0920d1191d47c3ff9a02f6595ce048e96.jpg:p',
    ],
    agentName: 'Abbey Mews Estates',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(721540).png',
    agentPhoneNumber: '+88 35 3584 2575',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'Polytechni',
      addressLine2: 'Bayazid',
      city: 'Chattogram',
      country: 'Bangladesh',
      postCode: '2245',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: false,
      balcony: true,
      parking: true,
      garage: true,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: false,
      electricity: true,
      generator: true,
      solar: false,
      airConditioning: true,
      swimmingPool: true,
      garden: true,
      gym: false,
      elevator: false,
      cableTv: false,
      internet: false,
      laundry: false,
      cleaningService: true,
      cafetoria: true,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: false,
      conferenceRoom: false,
      staffRoom: false,
      servantRoom: true,
    },

    postType: 'featured',
    purpose: 'rent',
    propertyCategory: 'commercial',
    propertyType: 'floor',
    propertyTitle: '5000 sqft floor',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 200000,
    propertyBedrooms: 6,
    propertyBathrooms: 5,
    propertyFloorNumber: 6,
    propertySqft: 5000,
    propertyFurnished: true,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/78304a1ce4f1577df26c204bfea39accc2133635.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/ca66433bcee487fe9d36f348771a464fe255be41.jpg',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/78304a1ce4f1577df26c204bfea39accc2133635.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/a485b8c50197b7cecadf8cc415a238722ade07a2.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/eb28dde6541e0dbbe693aa11b1d5ef5fca721d2f.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/ba35ccc95be51014b008048b7192d4bf21a55e08.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/2dbc0a5fa1a0b9d24b427192e39dd6091770d707.jpg:p',
    ],
    agentName: 'Alexander Property',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(333691).png',
    agentPhoneNumber: '+88 35 3756 7595',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'Paikpara',
      addressLine2: 'Monipuripara',
      city: 'Mymensingh',
      country: 'Bangladesh',
      postCode: '3215',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: true,
      balcony: true,
      parking: false,
      garage: true,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: false,
      electricity: false,
      generator: true,
      solar: false,
      airConditioning: true,
      swimmingPool: true,
      garden: true,
      gym: true,
      elevator: false,
      cableTv: false,
      internet: false,
      laundry: false,
      cleaningService: true,
      cafetoria: true,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: false,
      conferenceRoom: false,
      staffRoom: true,
      servantRoom: true,
    },

    postType: 'basic',
    purpose: 'rent',
    propertyCategory: 'commercial',
    propertyType: 'apartment',
    propertyTitle: '3 bedrooms apartment',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 20000,
    propertyBedrooms: 3,
    propertyBathrooms: 2,
    propertyFloorNumber: 8,
    propertySqft: 1000,
    propertyFurnished: false,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/e72261d6323a62eb8f32be28bf6b069773dbc3f4.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/53373b3bbfebcf22b774bb002ba71c9717a6253d.jpg',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/e72261d6323a62eb8f32be28bf6b069773dbc3f4.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/d082c2d14ee0c3aae8a625947694350a183ee1b9.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/ef8528c1bfce4f44fc1a979dd0b12cce6e4ab45f.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/c55893279ec0ab8a6e4e93151bd07837d1c8f4b2.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/7e8bfccd69e10eecb956ff9f13011f17895c0daa.jpg:p',
    ],
    agentName: 'Bigmove Estate',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(306373).png',
    agentPhoneNumber: '+88 745 3456 7595',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'Aziz Moholla',
      addressLine2: 'Mohammadpur',
      city: 'Mymensingh',
      country: 'Bangladesh',
      postCode: '3225',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: true,
      balcony: true,
      parking: false,
      garage: false,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: false,
      electricity: false,
      generator: true,
      solar: false,
      airConditioning: true,
      swimmingPool: true,
      garden: true,
      gym: true,
      elevator: true,
      cableTv: false,
      internet: false,
      laundry: false,
      cleaningService: true,
      cafetoria: true,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: false,
      conferenceRoom: false,
      staffRoom: true,
      servantRoom: true,
    },

    postType: 'featured',
    purpose: 'buy',
    propertyCategory: 'residential',
    propertyType: 'plot',
    propertyTitle: '4 bedrooms flot',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 700000,
    propertyBedrooms: 4,
    propertyBathrooms: 4,
    propertyFloorNumber: 6,
    propertySqft: 2000,
    propertyFurnished: true,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/7f9cea14943bacb38e7dd92cd9bf43aa3182382f.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/135c3f332e66c4c17495664836014533e2cc0a4f.jpg',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/7f9cea14943bacb38e7dd92cd9bf43aa3182382f.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/681b9df218fc269eda4049b9eecb5c6ac5f64abd.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/d32040e7507330dd7a1e99f14aa146dc6b6f4c22.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/5de83eb8ad37a4826119debc9c02e8d8323923a2.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/55f9ab292aec4b965f53991ec1a45672ce7d15ea.jpg:p',
    ],
    agentName: 'Castle Estate',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(74755).jpeg',
    agentPhoneNumber: '+88 745 3256 7895',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'Konapara',
      addressLine2: 'Demra',
      city: 'Mymensingh',
      country: 'Bangladesh',
      postCode: '3220',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: true,
      balcony: true,
      parking: true,
      garage: false,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: false,
      electricity: false,
      generator: true,
      solar: false,
      airConditioning: true,
      swimmingPool: true,
      garden: true,
      gym: true,
      elevator: false,
      cableTv: false,
      internet: false,
      laundry: false,
      cleaningService: true,
      cafetoria: true,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: false,
      conferenceRoom: false,
      staffRoom: true,
      servantRoom: true,
    },

    postType: 'basic',
    purpose: 'rent',
    propertyCategory: 'commercial',
    propertyType: 'office',
    propertyTitle: '3000 sqft office',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 70000,
    propertyBedrooms: 3,
    propertyBathrooms: 3,
    propertyFloorNumber: 2,
    propertySqft: 3000,
    propertyFurnished: true,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/de337baa463054b12fdcf6dde3de44fe64a4a534.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/8eecf0d21c8f5a90cc961882f35b3e0ccf51e5b3.jpg',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/de337baa463054b12fdcf6dde3de44fe64a4a534.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/a2f1bdbba7be2ae50bc555aaf9d8d4338f9f750b.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/5ab50e9525108556eca6d02f955de81c2d7f9620.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/04dd01ab8a855f7fc79c5d1a1114e92310b67e4f.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/2ab98d3b23c59dcc09937d691440ce9fd91d7c77.jpg:p',
    ],
    agentName: 'Dimension Estates',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(73725).png',
    agentPhoneNumber: '+88 745 3256 3545',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'D Block',
      addressLine2: 'Shahjalal Upashahar',
      city: 'Sylhet',
      country: 'Bangladesh',
      postCode: '4215',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: true,
      balcony: true,
      parking: true,
      garage: false,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: false,
      electricity: false,
      generator: true,
      solar: false,
      airConditioning: true,
      swimmingPool: true,
      garden: true,
      gym: true,
      elevator: false,
      cableTv: false,
      internet: false,
      laundry: false,
      cleaningService: true,
      cafetoria: true,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: false,
      conferenceRoom: false,
      staffRoom: true,
      servantRoom: true,
    },

    postType: 'basic',
    purpose: 'rent',
    propertyCategory: 'residential',
    propertyType: 'apartment',
    propertyTitle: 'Three bedrooms apartment',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 18000,
    propertyBedrooms: 3,
    propertyBathrooms: 2,
    propertyFloorNumber: 5,
    propertySqft: 1000,
    propertyFurnished: false,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/5340b120c5793c18da12b975219072f366242374.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/8eecf0d21c8f5a90cc961882f35b3e0ccf51e5b3.jpg',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/5340b120c5793c18da12b975219072f366242374.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/8cf465162238d3eace191dc5b46ed370affbf342.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/f8f8035780cfe26dfa41a29e93eb3b29ef7c947f.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/d8dcae6e3e597af58438a8d6a644799aba38c730.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/863d37eb06d260870e367e32e26ea681e4170be5.jpg:p',
    ],
    agentName: 'Stirling Ackroyd',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(727051).png',
    agentPhoneNumber: '+88 745 5235 3545',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'F Block',
      addressLine2: 'Shahjalal Upashahar',
      city: 'Sylhet',
      country: 'Bangladesh',
      postCode: '4215',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: true,
      balcony: true,
      parking: true,
      garage: false,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: false,
      electricity: false,
      generator: true,
      solar: false,
      airConditioning: true,
      swimmingPool: true,
      garden: true,
      gym: true,
      elevator: false,
      cableTv: false,
      internet: false,
      laundry: false,
      cleaningService: true,
      cafetoria: true,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: false,
      conferenceRoom: false,
      staffRoom: true,
      servantRoom: true,
    },

    postType: 'featured',
    purpose: 'buy',
    propertyCategory: 'residential',
    propertyType: 'apartment',
    propertyTitle: 'Four bedrooms apartment',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 40000,
    propertyBedrooms: 3,
    propertyBathrooms: 2,
    propertyFloorNumber: 5,
    propertySqft: 1000,
    propertyFurnished: false,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/e9d700acabbc02891eceb4cb847e5caf2ae74d5f.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/9f8fa8e74e5195ac1ddd872844bbe0b636e35237.jpg',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/e9d700acabbc02891eceb4cb847e5caf2ae74d5f.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/1461f553fd65f0daf3e4716ea70bca8e3bdce3b4.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/e0ec8439d9c283e53d8463252267727e1b152f5d.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/276871dc26b0e0f571d277e345726e6d7c397af9.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/863d37eb06d260870e367e32e26ea681e4170be5.jpg:p',
    ],
    agentName: 'Mansions Real Estate',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(126725).png',
    agentPhoneNumber: '+88 745 5235 3468',
  },
  {
    propertyAddress: {
      coordinates: {
        lat: 0,
        lng: 0,
      },
      addressLine1: 'C Block',
      addressLine2: 'Shahjalal Upashahar',
      city: 'Sylhet',
      country: 'Bangladesh',
      postCode: '4215',
    },
    propertyFeatures: {
      gasline: true,
      reception: false,
      tiledFloor: true,
      terrace: true,
      balcony: true,
      parking: true,
      garage: false,
      fireExit: true,
      fireProtection: true,
      water: true,
      hotWater: false,
      electricity: false,
      generator: true,
      solar: false,
      airConditioning: true,
      swimmingPool: true,
      garden: true,
      gym: true,
      elevator: false,
      cableTv: false,
      internet: false,
      laundry: false,
      cleaningService: true,
      cafetoria: true,
      securityStaff: true,
      officeRoom: true,
      executiveRoom: true,
      managerRoom: false,
      conferenceRoom: false,
      staffRoom: true,
      servantRoom: true,
    },

    postType: 'featured',
    purpose: 'rent',
    propertyCategory: 'residential',
    propertyType: 'apartment',
    propertyTitle: '1250 sqft apartment',
    propertyDescription:
      "Recognize the best when youre in Dhanmondi. Filled with restaurants, banks, shopping centers and recreational zones, the area is complete with all the amenities one could ask for. People from various places in the city come to the area on weekends. It makes sense since theres so much to do here. Built in great design with a spectacular outlook, this apartment boasts much more than meets the eye. With creatively structured rooms and intelligent architectural cuts, residents will know what it's like to live in pride. There are three bedrooms here and two of them have washrooms attached. One of them has a balcony attached. You also get separate spaces to be used as the dining and the drawing areas. There is also an attendant's bedroom and bathroom available within the abode. ",
    propertyPrice: 20000,
    propertyBedrooms: 3,
    propertyBathrooms: 2,
    propertyFloorNumber: 4,
    propertySqft: 1250,
    propertyFurnished: false,
    propertyFeaturedImage:
      'https://lid.zoocdn.com/u/2400/1800/6f0631487ee2920f8b89dd3b58d3ccea2c9072f5.jpg:p',
    propertyFloorPlanImage:
      'https://lid.zoocdn.com/u/2400/1800/9f8fa8e74e5195ac1ddd872844bbe0b636e35237.jpg',
    propertyImages: [
      'https://lid.zoocdn.com/u/2400/1800/6f0631487ee2920f8b89dd3b58d3ccea2c9072f5.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/2029e1e0340ed28307c61631a9e27286d8cfb5e3.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/9df36656a5b3ceda0ca0f773c6b979a2a2e785ec.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/de168c090c2febba6a90c4713a97c803b6522514.jpg:p',
      'https://lid.zoocdn.com/u/2400/1800/07521e11f2cd13f9511ac7be9db82898ca8d2485.jpg:p',
    ],
    agentName: 'Montels',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(74627).jpeg',
    agentPhoneNumber: '+88 745 3545 8546',
  },
]

const demoAgent = [
  {
    agentName: 'Benham and Reeves',
    agentEmail: 'info@benhams.com',
    agentPhoneNumber: '+44 20 3463 7502',
    agentWebsite: 'https://www.benhams.com/',
    agentLogo: 'https://st.zoocdn.com/zoopla_static_agent_logo_(634289).png',
    agentAddress: {
      addressLine1: 'Agargaon, Radio',
      addressLine2: '',
      city: 'Dhaka',
      country: 'Bangladesh',
      postCode: '1215',
      coordinates: {
        lat: 0,
        lng: 0,
      },
      agentSocialProfile: {
        facebook: 'https://www.facebook.com/benhams.com',
        twitter: 'https://twitter.com/benhams',
        instagram: 'https://www.instagram.com/benhams/',
        linkedin: 'https://www.linkedin.com/company/benhams/',
      },
      agentDescription:
        'Established in 1958, Benham and Reeves are one of the oldest independent agents in Hampstead. With coverage across Hampstead, West Hampstead, St Johns Wood and Belsize Park, tenants and landlords can be assured that they will find here an experienced lettings, sales and property management service. With our flagship office in Heath Street, we know that executives from FTSE and Fortune 500 companies like to live in the very best period conversions, apartments and family houses. Making up over two thirds of our tenants, they benefit from our extensive knowledge of the NW3, NW6 and NW8 postcodes. Many local landlords have been our clients for 20+ years.',
      agentGallery: [
        'https://st.zoocdn.com/zpg_agent_static_agent_profile_images_(62759558).jpg',
      ],
    },
  },
]

const demoPlans = [
  {
    name: 'silver',
    price: 5000,
    duration: 1,
    features: {
      property: {
        basic: 50,
        featured: 10,
      },
    },
  },
  {
    name: 'gold',
    price: 10000,
    duration: 2,
    features: {
      property: {
        basic: 100,
        featured: 20,
      },
    },
  },
  {
    name: 'platinum',
    price: 15000,
    duration: 5,
    features: {
      property: {
        basic: 150,
        featured: 30,
      },
    },
  },
]

module.exports = { defaultUsers, demoProperties, demoAgent }
